#!/bin/bash

#kill process with previous wednesday-bot
pid=$(ps -x | pgrep -f "[w]ednesday.py")
echo "sleep, wednesday-bot"
echo "killing process with pid: ${pid}"
if [ -z ${pid} ]; then
    echo "wednesday-bot was not running"
else
    kill ${pid}
fi
echo "
...
"
sleep 1

#pull latest from git
echo "pulling latest from git:"
git pull
echo "
...
"
sleep 1

#start updated wednesday-bot
echo "awaken, wednesday-bot"
./run

