#!/bin/bash

#kill process with previous wednesday-bot
pid=$(ps -x | pgrep -f "[w]ednesday.py")
if [ -z ${pid} ]; then
    echo "wednesday-bot was not running"
else
    echo "sleep, wednesday-bot"
    echo "killing process with pid: ${pid}"
    kill ${pid}
fi
